"""Prompt Templates and Pydantic Schemas for CodeMentor AI.

This module is responsible for:
1. Defining the structured output data models using Pydantic.
2. Formulating the system instructions for CodeMentor AI.
3. Assembling the RAG-augmented prompt containing student code, error context,
   and retrieved knowledge base documentation.

EDUCATIONAL NOTE FOR VIVA:
- Why Strict Structured JSON?
  In modern LLM applications, downstream services (like a web frontend or database)
  cannot reliably parse arbitrary conversational free text. By constraining the LLM
  to return valid JSON validated through a Pydantic schema, we guarantee that all
  required fields (explanation, cause, corrected code, etc.) are always present and correctly typed.
- Why RAG In Context?
  Rather than asking the LLM to rely solely on internal parametric memory, we inject
  retrieved reference documentation directly into the prompt. The LLM acts as an
  intelligent synthesis engine over our trusted knowledge base.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


# -----------------------------------------------------------------------------
# Pydantic Schemas
# -----------------------------------------------------------------------------

class SourceItem(BaseModel):
    """Metadata for a retrieved knowledge chunk used in the analysis."""
    source: str = Field(..., description="File path of the knowledge document.")
    score: float = Field(..., description="Cosine similarity score.")


class CodeAnalysisResult(BaseModel):
    """Structured response model generated by CodeMentor AI."""
    error_type: str = Field(
        ...,
        description="The identified error category (e.g. IndexError, SyntaxError, LogicError).",
    )
    explanation: str = Field(
        ...,
        description="Clear, student-friendly explanation of what the error means.",
    )
    cause: str = Field(
        ...,
        description="The root cause of the error in the student's specific code.",
    )
    concept: str = Field(
        ...,
        description="The primary programming concept involved (e.g. Python List Indexing).",
    )
    corrected_code: str = Field(
        ...,
        description="The corrected version of the student's code.",
    )
    learning_tip: str = Field(
        ...,
        description="A practical debugging or coding tip to avoid this issue in the future.",
    )
    practice_question: str = Field(
        ...,
        description="One short, targeted practice question to reinforce understanding.",
    )
    sources: List[SourceItem] = Field(
        default_factory=list,
        description="List of knowledge base sources retrieved by RAG.",
    )


class CodeAnalysisRequest(BaseModel):
    """Input request model for code analysis (used by API and services)."""
    language: str = Field(..., description="Programming language of the code.")
    code: str = Field(..., description="Source code submitted by the student.")
    error_message: str = Field(
        default="",
        description="Optional compiler/runtime error message or problem description.",
    )

    @field_validator("language")
    @classmethod
    def validate_language(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Programming language must not be empty.")
        return v.strip()

    @field_validator("code")
    @classmethod
    def validate_code(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Code snippet must not be empty.")
        return v.strip()


# -----------------------------------------------------------------------------
# System Prompt
# -----------------------------------------------------------------------------

SYSTEM_PROMPT = """You are CodeMentor AI, an expert programming tutor and debugging assistant.
Your goal is to guide students and early-career software developers through programming concepts,
debugging runtime errors, and building solid programming mental models.

Pedagogical Principles:
1. Be encouraging, clear, and educational. Never mock or use condescending tone.
2. Explain the root cause of the error intuitively, highlighting what Python/the language was expecting.
3. Identify the core programming concept (e.g. "Zero-Based Indexing", "Off-by-One Error").
4. Provide the minimal corrected code needed to fix the issue. DO NOT gratuitously rewrite
   working parts of the student's code or replace simple code with complex abstractions.
5. Provide a practical learning tip to help them remember the concept.
6. Provide ONE short, engaging practice question with a clear answer to test their understanding.
7. GROUND YOUR RESPONSE IN THE RETRIEVED KNOWLEDGE BASE CONTEXT whenever applicable.

CRITICAL INSTRUCTION FOR OUTPUT:
You must respond ONLY with a single valid JSON object adhering strictly to this schema:
{
  "error_type": "string",
  "explanation": "string",
  "cause": "string",
  "concept": "string",
  "corrected_code": "string",
  "learning_tip": "string",
  "practice_question": "string"
}

Do not include any text, greetings, markdown fences, or commentary outside the JSON object.
"""


def format_retrieved_context(retrieved_chunks: List[Dict[str, Any]]) -> str:
    """Formats a list of retrieved chunk dictionaries into a readable context block."""
    if not retrieved_chunks:
        return "No specific documents found in the local knowledge base."

    formatted_sections: List[str] = []
    for idx, chunk in enumerate(retrieved_chunks, 1):
        source = chunk.get("source", "unknown")
        text = chunk.get("text", "").strip()
        formatted_sections.append(
            f"--- Document [{idx}] (Source: {source}) ---\n{text}"
        )

    return "\n\n".join(formatted_sections)


def build_analysis_prompt(
    language: str,
    code: str,
    error_message: str = "",
    retrieved_chunks: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """Assembles the complete user prompt incorporating RAG context and student inputs."""
    context_text = format_retrieved_context(retrieved_chunks or [])
    error_section = error_message.strip() if error_message and error_message.strip() else "None provided (Code review/explanation requested)."

    prompt = f"""RETRIEVED KNOWLEDGE BASE CONTEXT:
============================================================
{context_text}
============================================================

STUDENT SUBMISSION:
------------------------------------------------------------
Programming Language: {language}

Error Message / Problem:
{error_section}

Submitted Code:
```{language.lower()}
{code}
```
------------------------------------------------------------

Please analyze the student's code using the retrieved knowledge base context.
Identify the error or improvement areas, explain the root cause, provide corrected code,
and respond strictly in the required JSON format.
"""
    return prompt
